coordinator=true
# node-scheduler.include-coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/etc/trino/tls/keystore.jks
http-server.https.keystore.key=qazwsx
discovery.uri=http://coordinator:8080
query.max-memory=5GB
query.max-memory-per-node=1GB
task.concurrency=16
http-server.authentication.type=PASSWORD
internal-communication.shared-secret=wmalsto4lIYGYiedc8iq83qMGI7+KOeApCltKWIAOrLVIs53AHqcLZBqfW7BmPKv92hRKypkUvvGV9yhJ8cr4+9S4/dmPlFfvxH1uv2/ZihvAcFpnF661HG5074aGdKkVSTVSNwQK/e0MoffegezMKkZLKPI71tLnDfq/0jn6CF3MAASVxZpMNmFp6nyPIQlAHFGvbnF3PpEH/tjjZmoIGJqIUsscvMMKVP5Ch2syYAIVY3cEDccpdmUt8/+HRx3ZANanWTo9LRzv5494pTA6QM0PzkxeNHpoBDj/+gQq8XG22HKoyy58zX7tF9aHXx9xJJxtyYjLUDb8bHtzeQ2xXipfsAj9q1QBcdmMNzCFqk1aQ+Z/qv9xIRkUQ1+xGbSOOvCR2a0u+k6Rtf5rNDzNThY3NrNiT493lXgiG1997CGpGSVItTPUZCKjvsU1Isn/0SxrlhXbCnyDP4xBeUc089F4P8HROWPCsfbaQSyYgo8881Aaxj87bTxbQ35DIC8rEwmwNsh4PvqaFuk63cFHmrP8s3ZyfOlt9+LZ7E4foUOBABzetQJ7cvV8bJVrcwXXUvwuONegnNDIaEXLh259v9Caj5FJSrZ3OAPhVmae4aFaXOZc8d40+EuPhU/VWFoL4lEsDHz3GYq+h3yz8OYdVvMfFXUl+cJy0HMLy84+Ig=